"""init schema (clean)

Revision ID: 2d7d217ff197
Revises: 
Create Date: 2025-08-24 14:33:37.875760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7d217ff197'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('monto_presupuestado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contrasena', sa.String(length=200), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_id', 'code', name='uq_hier_dim_code')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('agg_op', sa.String(length=2), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_id', 'code', name='uq_member_dim_code')
    )
    op.create_table('hecho_financiero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('costcenter_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['costcenter_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchy_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_id', sa.Integer(), nullable=False),
    sa.Column('parent_member_id', sa.Integer(), nullable=True),
    sa.Column('child_member_id', sa.Integer(), nullable=False),
    sa.Column('order_nbr', sa.Integer(), nullable=False),
    sa.Column('unary_op', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['hierarchies.id'], ),
    sa.ForeignKeyConstraint(['parent_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hierarchy_id', 'parent_member_id', 'child_member_id', name='uq_edge_unique')
    )
    op.create_table('member_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('alias_tab', sa.String(length=64), nullable=False),
    sa.Column('alias_val', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'alias_tab', name='uq_member_alias_tab')
    )
    op.create_table('member_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('prop_key', sa.String(length=64), nullable=False),
    sa.Column('prop_val', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'prop_key', name='uq_member_prop_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_properties')
    op.drop_table('member_aliases')
    op.drop_table('hierarchy_edges')
    op.drop_table('hecho_financiero')
    op.drop_table('members')
    op.drop_table('hierarchies')
    op.drop_table('categoria')
    op.drop_table('usuario')
    op.drop_table('presupuesto')
    op.drop_table('dimensions')
    # ### end Alembic commands ###
